chore(s6-overlay/init-cabal): Refactor directory creation and ownership setting
- run: Ensure CABAL_DIR is created and set ownership only if it doesn't exist

run-ci

diff --git a/code-server/root/etc/s6-overlay/s6-rc.d/init-cabal/run b/code-server/root/etc/s6-overlay/s6-rc.d/init-cabal/run
--- a/code-server/root/etc/s6-overlay/s6-rc.d/init-cabal/run
+++ b/code-server/root/etc/s6-overlay/s6-rc.d/init-cabal/run
@@ -43,17 +43,19 @@ if [ -e "$CABAL_DIR" ] && [ ! -d "$CABAL_DIR" ]; then
   echo "WARN: $CABAL_DIR exists as a file. Removing and creating directory."
   rm -f "$CABAL_DIR"
 fi
+
+# Check if CABAL_DIR exists, if not create it
 if [ ! -d "$CABAL_DIR" ]; then
   echo "INFO: Creating directory: $CABAL_DIR"
   if ! mkdir -p "$CABAL_DIR"; then
     echo "WARN: Failed to create directory $CABAL_DIR"
   fi
-fi
 
-# Set ownership of CABAL_DIR to PUID:PGID
-echo "INFO: Setting ownership of $CABAL_DIR to ${PUID}:${PGID}"
-if ! chown -R "${PUID}:${PGID}" "$CABAL_DIR"; then
-  echo "WARN: Failed to set ownership for $CABAL_DIR"
+  # Set ownership of CABAL_DIR to PUID:PGID
+  echo "INFO: Setting ownership of $CABAL_DIR to ${PUID}:${PGID}"
+  if ! chown -R "${PUID}:${PGID}" "$CABAL_DIR"; then
+    echo "WARN: Failed to set ownership for $CABAL_DIR"
+  fi
 fi
 
 if is_truthy "$CABAL_UPDATE_PACKAGES"; then
