chore: code-server
run-ci

diff --git a/code-server/Dockerfile b/code-server/Dockerfile
--- a/code-server/Dockerfile
+++ b/code-server/Dockerfile
@@ -1,24 +1,51 @@
 FROM lscr.io/linuxserver/code-server:latest
 
-ENV DEBIAN_FRONTEND=noninteractive
-ENV PUID=1000
-ENV PGID=1000
-ENV TZ=America/Toronto
-ENV DEFAULT_WORKSPACE=/config/workspace
+# Set environment variables
+ENV DEBIAN_FRONTEND=noninteractive \
+    PUID=1000 \
+    PGID=1000 \
+    TZ=America/Toronto \
+    DEFAULT_WORKSPACE=/config/workspace \
 
-RUN apt-get update && apt-get upgrade -y && apt-get install build-essential curl wget unzip lsb-release apt-transport-https -y
-RUN curl -fsSL https://fnm.vercel.app/install | bash
-RUN . /config/.bashrc
-RUN fnm install 22
-RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-RUN wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
-RUN dpkg -i packages-microsoft-prod.deb
-RUN apt-get update
-RUN apt-get install msopenjdk-21
-RUN rm packages-microsoft-prod.deb
-RUN apt-get clean && \
+# Combine all RUN commands into one to minimize layers
+RUN set -ex && \
+    \
+    # Update and upgrade package lists
+    apt-get update && \
+    apt-get upgrade -y && \
+    \
+    # Install necessary packages
+    apt-get install -y --no-install-recommends \
+        apt-transport-https && \
+        build-essential \
+        curl \
+        lsb-release \
+        unzip \
+        wget \
+    \
+    # Install Fast Node Manager (fnm) and Node.js version 22
+    curl -fsSL https://fnm.vercel.app/install | bash && \
+    . /config/.bashrc && \
+    fnm install 22 && \
+    \
+    # Install Rust using rustup
+    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
+    \
+    # Install Microsoft's OpenJDK 21
+    wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
+    dpkg -i packages-microsoft-prod.deb && \
+    rm packages-microsoft-prod.deb && \
+    apt-get update && \
+    apt-get install -y --no-install-recommends msopenjdk-21 && \
+    \
+    # Clean up APT when done
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/* && \
+    \
+    # Remove temporary and unnecessary files
     rm -rf \
-    /config/* \
-    /tmp/* \
-    /var/lib/apt/lists/* \
-    /var/tmp/*
+        /tmp/* \
+        /var/tmp/*
+
+# Expose the necessary port
+EXPOSE 8443
